feat: change default font to Louis Goerge Cafe (#6)
unsri-hackers/ecommerce-ui pull request #15
Opened 2021-05-29 16:30 UTC by LordAldi

Fixes #6

2021-05-29 16:48 UTC, ariefrahmansyah requested changes
Please put the font files in `assets/fonts/Louis-George-Cafe` for better organization.

2021-05-29 16:48 UTC, ariefrahmansyah commented on src/assets/scss/font.scss
> +@font-face {
Add line break here

2021-05-29 16:48 UTC, ariefrahmansyah commented on src/assets/scss/font.scss
> +@font-face {
Add line break here

2021-05-29 16:48 UTC, ariefrahmansyah commented on src/assets/scss/font.scss
> +*,
Add line break here.

2021-05-29 18:42 UTC, ariefrahmansyah approved these changes
LGTM

2021-05-30 04:25 UTC, fadelarmando approved these changes
LGTM

2021-05-30 04:44 UTC, merged