feat: Add footer component (#9)
unsri-hackers/ecommerce-ui pull request #18
Opened 2021-05-30 15:15 UTC by fadelarmando

- add logo in footer 
- can't click list of page
- no responsive

2021-05-30 16:11 UTC, LordAldi requested changes
Thanks for the update. I've left some comments and suggestions.
overall already look so good just need fix something minor and maybe make responsive

2021-05-30 16:11 UTC, LordAldi commented on src/components/footer/Logo.js
> +export default Logo;
its the same with Logo.js in `./src/component/header` why create new file instead of import from that file?

2021-05-30 16:11 UTC, LordAldi commented on src/components/footer/Footer.js
> +import { Col, Input, Row } from "antd";
Input never used, you can delete it

2021-05-30 16:11 UTC, LordAldi commented on src/components/footer/Footer.scss
> +ul{
add line break

2021-05-30 16:11 UTC, LordAldi commented on src/components/footer/Footer.scss
> +.footer-content{
add line break

2021-05-30 16:11 UTC, LordAldi commented on src/components/footer/Footer.scss
> +.footer-col-logo{
add line break after every class

2021-05-31 08:26 UTC, fadelarmando commented on src/components/footer/Footer.js
> +import { Col, Input, Row } from "antd";
i already deleted it

2021-05-31 08:27 UTC, fadelarmando commented on src/components/footer/Logo.js
> +export default Logo;
sorry my mistake, i have changed it

2021-05-31 08:28 UTC, fadelarmando commented on src/components/footer/Footer.scss
> +ul{
I have done it

2021-05-31 08:28 UTC, fadelarmando commented on src/components/footer/Footer.scss
> +.footer-content{
I have done it

2021-05-31 08:28 UTC, fadelarmando commented on src/components/footer/Footer.scss
> +.footer-col-logo{
I have done it

2021-05-31 10:48 UTC, ariefrahmansyah approved these changes
Mantabb

2021-05-31 20:15 UTC, LordAldi approved these changes
LGTM

2021-06-01 06:01 UTC, merged