Feature/3 login page
unsri-hackers/ecommerce-ui pull request #23
Opened 2021-06-01 04:59 UTC by LordAldi

fixes (#3)
![Screenshot_2021-06-01 deuvox](https://user-images.githubusercontent.com/49033706/120268826-c2ac7400-c2d0-11eb-899d-37f50f7df9ef.png)
![Screenshot_2021-06-01 deuvox(1)](https://user-images.githubusercontent.com/49033706/120268831-c5a76480-c2d0-11eb-9a4a-0eee71c86e2e.png)

2021-06-03 03:29 UTC, ariefrahmansyah requested changes

2021-06-03 03:29 UTC, ariefrahmansyah commented on craco.config.js
> +              "@font-family": "LouisGoergeCafe",
Typo? It should be `LouisGeorgeCafe`, right?

2021-06-03 03:29 UTC, ariefrahmansyah commented on src/components/loginForm/LoginForm.js
> +import React from "react";
LoginForm only used by `pages/login/Login.js` so I propose to move this component to this location:

`pages/login/components/form/LoginForm.js`

Page-specific components should be placed inside of it's page folder.

2021-06-04 12:04 UTC, FadellMuhammad approved these changes

2021-06-04 12:13 UTC, ariefrahmansyah approved these changes

2021-06-04 12:13 UTC, merged