add feature startedPage
unsri-hackers/ecommerce-ui pull request #29
Opened 2021-06-03 08:10 UTC by FadellMuhammad

2021-06-03 16:59 UTC, LordAldi requested changes

2021-06-03 16:59 UTC, LordAldi commented on src/App.js
> +      <Footer />
jgn diubah lagi routerny, tarok started page dibawah Home di dalem tag layout, kayna header dan footer sudah masuk ke tag layout itu

2021-06-03 16:59 UTC, LordAldi commented on src/components/header/Header.scss
> +  justify-content: center;
ini knapa headerny diubah jugo? ad yg salah?

2021-06-03 16:59 UTC, LordAldi commented on src/components/startedPage/StartedPage.js
> +export default StartedPage;
karena started page ini page bukan component, jadi buatny di folder `./src/pages/startedPage/startedPage.js`

2021-06-03 16:59 UTC, LordAldi commented on src/components/startedPage/startedPage.scss
> +.startedPage{
coba ganti fileny dari startedPage.scss ke startedPage.less karena ant.design pakeny less bukan scss.

2021-06-03 16:59 UTC, LordAldi commented on src/components/startedPage/startedPage.scss
> +@media screen and (max-width: 1380px) {
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
disitu ad list variable default yg sudah di pake di file croco.config.js 
breakpoint smoin dgn yg punyo ant.design supaya seragam breakpointny, search bee screen-xs, screen-sm di link itu

2021-06-03 17:00 UTC, LordAldi commented on src/components/startedPage/startedPage.scss
> +@media screen and (max-width: 1380px) {
1 lagi, sebelum push pastike dlu dk ado error atau warning, kalo ad error dan warning pasti gagal check deploy yg dibawah sekali itu

2021-06-05 02:28 UTC, FadellMuhammad commented on src/components/header/Header.scss
> +  justify-content: center;
iyaa header sebelumnya gk pas tengah

2021-06-05 02:30 UTC, FadellMuhammad commented on src/components/startedPage/startedPage.scss
> +@media screen and (max-width: 1380px) {
ok

2021-06-05 13:57 UTC, closed without merging